import type { Account, SavingsGoal, Subscription, Transaction } from "./types";

function isoDaysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function isoDaysAhead(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

export function makeSeed() {
  const now = new Date().toISOString();

  const accounts: Account[] = [
    {
      id: "acc-checking",
      name: "Everyday Checking",
      type: "checking",
      balance: 4280.42,
      institution: "Sunrise Bank",
      color: "sky",
      createdAt: now,
    },
    {
      id: "acc-savings",
      name: "Emergency Fund",
      type: "savings",
      balance: 12500,
      apr: 4.2,
      institution: "Sunrise Bank",
      color: "mint",
      createdAt: now,
    },
    {
      id: "acc-investment",
      name: "Brokerage",
      type: "investment",
      balance: 38420.18,
      apr: 7,
      institution: "Vanguard",
      color: "violet",
      createdAt: now,
    },
    {
      id: "acc-credit-1",
      name: "Sapphire Card",
      type: "credit",
      balance: 2840.55,
      creditLimit: 12000,
      apr: 22.99,
      minimumPayment: 75,
      institution: "Chase",
      color: "coral",
      createdAt: now,
    },
    {
      id: "acc-credit-2",
      name: "Cashback Card",
      type: "credit",
      balance: 980.12,
      creditLimit: 6000,
      apr: 18.49,
      minimumPayment: 35,
      institution: "Capital One",
      color: "amber",
      createdAt: now,
    },
    {
      id: "acc-loan-car",
      name: "Auto Loan",
      type: "loan",
      balance: 14250,
      apr: 6.49,
      minimumPayment: 380,
      institution: "Local Credit Union",
      color: "stone",
      createdAt: now,
    },
    {
      id: "acc-loan-student",
      name: "Student Loan",
      type: "loan",
      balance: 21300,
      apr: 5.5,
      minimumPayment: 230,
      institution: "Federal",
      color: "rose",
      createdAt: now,
    },
  ];

  const transactions: Transaction[] = [
    { id: "t1", accountId: "acc-checking", amount: 4200, type: "income", category: "salary", merchant: "Acme Corp", date: isoDaysAgo(2), createdAt: now },
    { id: "t2", accountId: "acc-checking", amount: 1850, type: "expense", category: "rent", merchant: "Landlord", date: isoDaysAgo(5), createdAt: now },
    { id: "t3", accountId: "acc-checking", amount: 84.32, type: "expense", category: "groceries", merchant: "Whole Foods", date: isoDaysAgo(1), createdAt: now },
    { id: "t4", accountId: "acc-credit-1", amount: 12.5, type: "expense", category: "coffee", merchant: "Blue Bottle", date: isoDaysAgo(0), createdAt: now },
    { id: "t5", accountId: "acc-credit-1", amount: 47.8, type: "expense", category: "dining", merchant: "Sushi Place", date: isoDaysAgo(3), createdAt: now },
    { id: "t6", accountId: "acc-credit-2", amount: 132.4, type: "expense", category: "shopping", merchant: "Target", date: isoDaysAgo(4), createdAt: now },
    { id: "t7", accountId: "acc-checking", amount: 65, type: "expense", category: "fuel", merchant: "Shell", date: isoDaysAgo(6), createdAt: now },
    { id: "t8", accountId: "acc-checking", amount: 92.1, type: "expense", category: "utilities", merchant: "PG&E", date: isoDaysAgo(8), createdAt: now },
    { id: "t9", accountId: "acc-savings", amount: 500, type: "income", category: "savings-deposit", merchant: "Auto Transfer", date: isoDaysAgo(10), createdAt: now },
    { id: "t10", accountId: "acc-checking", amount: 500, type: "transfer", toAccountId: "acc-savings", category: "savings-deposit", date: isoDaysAgo(10), createdAt: now },
    { id: "t11", accountId: "acc-credit-1", amount: 22.99, type: "expense", category: "subscriptions", merchant: "Streaming Co", date: isoDaysAgo(12), createdAt: now },
    { id: "t12", accountId: "acc-checking", amount: 38, type: "expense", category: "fitness", merchant: "Equinox", date: isoDaysAgo(14), createdAt: now },
    { id: "t13", accountId: "acc-credit-2", amount: 56.2, type: "expense", category: "groceries", merchant: "Trader Joe's", date: isoDaysAgo(15), createdAt: now },
    { id: "t14", accountId: "acc-checking", amount: 200, type: "expense", category: "credit-payment", merchant: "Chase Sapphire", date: isoDaysAgo(18), createdAt: now },
    { id: "t15", accountId: "acc-checking", amount: 380, type: "expense", category: "loan-payment", merchant: "Auto Loan", date: isoDaysAgo(20), createdAt: now },
    { id: "t16", accountId: "acc-credit-1", amount: 18.4, type: "expense", category: "dining", merchant: "Chipotle", date: isoDaysAgo(7), createdAt: now },
    { id: "t17", accountId: "acc-checking", amount: 350, type: "income", category: "freelance", merchant: "Side Project", date: isoDaysAgo(11), createdAt: now },
    { id: "t18", accountId: "acc-credit-2", amount: 9.99, type: "expense", category: "subscriptions", merchant: "Cloud Storage", date: isoDaysAgo(22), createdAt: now },
  ];

  const subscriptions: Subscription[] = [
    {
      id: "s1",
      name: "Netflix",
      amount: 15.49,
      frequency: "monthly",
      category: "subscriptions",
      accountId: "acc-credit-1",
      nextChargeDate: isoDaysAhead(8),
      startDate: isoDaysAgo(420),
      active: true,
      color: "coral",
      icon: "Tv",
      createdAt: now,
    },
    {
      id: "s2",
      name: "Spotify Family",
      amount: 16.99,
      frequency: "monthly",
      category: "subscriptions",
      accountId: "acc-credit-1",
      nextChargeDate: isoDaysAhead(3),
      startDate: isoDaysAgo(800),
      active: true,
      color: "lime",
      icon: "Music",
      createdAt: now,
    },
    {
      id: "s3",
      name: "iCloud+ 2TB",
      amount: 9.99,
      frequency: "monthly",
      category: "subscriptions",
      accountId: "acc-credit-2",
      nextChargeDate: isoDaysAhead(12),
      startDate: isoDaysAgo(300),
      active: true,
      color: "sky",
      icon: "Cloud",
      createdAt: now,
    },
    {
      id: "s4",
      name: "Gym Membership",
      amount: 38,
      frequency: "monthly",
      category: "fitness",
      accountId: "acc-checking",
      nextChargeDate: isoDaysAhead(20),
      startDate: isoDaysAgo(180),
      active: true,
      color: "lime",
      icon: "Dumbbell",
      createdAt: now,
    },
    {
      id: "s5",
      name: "Adobe Creative Cloud",
      amount: 599.88,
      frequency: "yearly",
      category: "subscriptions",
      accountId: "acc-credit-1",
      nextChargeDate: isoDaysAhead(45),
      startDate: isoDaysAgo(700),
      active: true,
      color: "violet",
      icon: "Palette",
      createdAt: now,
    },
    {
      id: "s6",
      name: "ChatGPT Plus",
      amount: 20,
      frequency: "monthly",
      category: "subscriptions",
      accountId: "acc-credit-2",
      nextChargeDate: isoDaysAhead(6),
      startDate: isoDaysAgo(90),
      active: true,
      color: "mint",
      icon: "Sparkles",
      createdAt: now,
    },
    {
      id: "s7",
      name: "NYT",
      amount: 25,
      frequency: "monthly",
      category: "subscriptions",
      accountId: "acc-credit-2",
      nextChargeDate: isoDaysAhead(14),
      startDate: isoDaysAgo(500),
      active: true,
      color: "stone",
      icon: "Newspaper",
      createdAt: now,
    },
  ];

  const goals: SavingsGoal[] = [
    {
      id: "g1",
      name: "Emergency Fund",
      targetAmount: 18000,
      currentAmount: 12500,
      targetDate: isoDaysAhead(240),
      accountId: "acc-savings",
      monthlyContribution: 500,
      color: "mint",
      icon: "ShieldCheck",
      createdAt: now,
    },
    {
      id: "g2",
      name: "Japan Trip",
      targetAmount: 6000,
      currentAmount: 1450,
      targetDate: isoDaysAhead(360),
      monthlyContribution: 350,
      color: "coral",
      icon: "Plane",
      createdAt: now,
    },
    {
      id: "g3",
      name: "New Laptop",
      targetAmount: 2800,
      currentAmount: 920,
      targetDate: isoDaysAhead(150),
      monthlyContribution: 200,
      color: "violet",
      icon: "Laptop",
      createdAt: now,
    },
  ];

  return { accounts, transactions, subscriptions, goals };
}
